[build]
  command = "npm install && node node_modules/vite/bin/vite.js build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200